### ISSUE TITLE
bash: ./compile-x264.sh: 没有那个文件或目录

### ISSUE THREAD

**Issue by xiaodatao2007** [ShikinChen/video-editor#1]
_cd android/contrib
#先编译x264,如果失败需要先执行clean清除配置和缓存再编译
./compile-x264.sh clean
./compile-x264.sh arm64_

adb@xdt:~/video-editor/android/contrib$ cd android/contrib
adb@xdt:~/video-editor/android/contrib$ ./compile-x264.sh clean
bash: ./compile-x264.sh: 没有那个文件或目录

提示没有这个文件:compile-x264.sh?

感谢您的同源项目!

**Comment by ShikinChen** [comment]
忘记提交了 已经补回去了 最好重新执行 init-android.sh 拉取 x264源码
